### ISSUE TITLE
Can I use this with a-frame?

### ISSUE THREAD

**Issue by dzg** [FlamingoFilter/8gui#1]
This looks awesome!
But I’m using **8th Wall** with **a-frame** (not Three.js).
I tried 
`document.inspect(document.querySelector('a-scene'), 'scene')`
and 
`document.inspect(document.querySelector('a-scene').object3D, 'scene')`
but neither seems to work. 

Also 
```
const {scene} = XR8.Threejs.xrScene()
15:13:12.217 VM217024:1 Uncaught TypeError: Cannot destructure property 'scene' of 'XR8.Threejs.xrScene(...)' as it is null.
```

Thanks!!

**Comment by JonathannJacobs** [comment]
Eyh dzg, 8gui was intended to work with 8thwall, hence it's name.
Can you try setting the id of your scene with id="scene" and try using :
document.inspect(document.getElementById('scene'));

I'm always afraid of querySelector because it can return values or arrays and have unconsistent behaviour across some browsers.

**Comment by dzg** [comment]
AMAZING!

**Comment by dzg** [comment]
FTW 
```
document.inspect($('a-scene'))
```
